apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: blazecicd-client-hpa
  namespace: blazecicd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blazecicd-client-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
