apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: blazecicd-client-issuer
  namespace: blazecicd
spec:
  acme:
    email: ar.aldhafeeri11@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: blazecicd-client-private-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
